AesKey: 123456
spring:
  application:
    name: spring-cloud-learn
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_learn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server.ssl:
  key-store: classpath:ly.key
  key-store-password: 123456
  key-password: 123456
#  profiles:
#      active: dev